esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    then:
      - script.execute: ext1_coutdown
  on_shutdown:
    then:
      #Configure button matrix for ext1 interrupt
      - lambda: |-
          pinMode(32, OUTPUT);
          pinMode(26, OUTPUT);
          pinMode(27, OUTPUT);
          pinMode(14, OUTPUT);
          pinMode(12, OUTPUT);
          digitalWrite(32, HIGH);
          digitalWrite(26, HIGH);
          digitalWrite(27, HIGH);
          digitalWrite(14, HIGH);
          digitalWrite(12, HIGH);
          gpio_hold_en((gpio_num_t)32);
          gpio_hold_en((gpio_num_t)26);
          gpio_hold_en((gpio_num_t)27);
          gpio_hold_en((gpio_num_t)14);
          gpio_hold_en((gpio_num_t)12);

esp32:
  board: esp32dev
  framework:
    type: arduino

#set up battery sensor
sensor:
  - platform: adc
    pin: 36
    id: battery_level2
    name: "battery level"

# Enable logging
logger:

# Enable Home Assistant API
api:
  
ota:
  on_begin:
    then:
      - deep_sleep.prevent: ext1
  on_end:
    then:
      - deep_sleep.allow: ext1

deep_sleep:
  id: ext1
  #touch_wakeup: True
  esp32_ext1_wakeup:
    pins:
      - number: 37
        allow_other_uses: true
      - number: 38
        allow_other_uses: true
      - number: 39
        allow_other_uses: true
      - number: 34
        allow_other_uses: true
      - number: 35
        allow_other_uses: true
    mode: ANY_HIGH

script:
  - id: ext1_coutdown
    mode: restart
    then:
      - light.turn_on: back_light
      - delay: 1 min
      - light.turn_off: back_light
      - delay: 4 min
      - deep_sleep.enter: ext1

wifi:
  on_connect:
    - lvgl.widget.update: 
        id: lbl_wifi
        text_color: 0xFFFFFF
  on_disconnect:
    - lvgl.widget.update: 
        id: lbl_wifi
        text_color: 0xFF0000

esp32_improv:
  authorizer: none


captive_portal:

external_components:
  - source: github://pr#6363
    components: [ lvgl ]
    refresh: 0ms

spi:
  clk_pin: 18
  mosi_pin: 23
i2c:
  sda: 19
  scl: 22
  scan: False
  frequency: 400kHz

output:
  - platform: gpio
    pin: 
      number: 10
    id: LCD_EN
  - platform: gpio
    pin: 
      number: 32
      allow_other_uses: true
    id: sw_1
  - platform: gpio
    pin: 
      number: 26
      allow_other_uses: true
    id: sw_2
  - platform: gpio
    pin: 
      number: 27
      allow_other_uses: true
    id: sw_3
  - platform: gpio
    pin: 
      number: 14
      allow_other_uses: true
    id: sw_4
  - platform: gpio
    pin: 
      number: 12
      allow_other_uses: true
    id: sw_5
  - platform: gpio
    pin: 25
    id: IR_VCC

# Define a PWM output on the ESP32

  - platform: ledc
    pin:
      number: 4
      inverted: true
    id: gpio_4_backlight_pwm

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: gpio_4_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
    on_turn_on:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
            - lvgl.pause:
    on_turn_off:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - delay: 1s
      - lvgl.pause:
          show_snow: true

display:
  - platform: ili9xxx
    model: ili9341
    id: LCD
    dc_pin: 9
    cs_pin: 5
    dimensions: 240X320
    auto_clear_enabled: false
    update_interval: never

touchscreen:
  - platform: ft63x6
    id: my_touch
    display: LCD
    address: 0x38
    calibration:
      x_min: 0
      x_max: 237
      y_min: 0
      y_max: 319
    transform:
      mirror_x: true
      mirror_y: true
    on_release:
      then:
        - script.execute: ext1_coutdown
        - if:
            condition: lvgl.is_paused
            then:
              - lvgl.resume:
              - lvgl.widget.redraw:

lvgl:
  displays:
    - display_id: LCD
  touchscreens:
    - touchscreen_id: my_touch
  buffer_size: 25%
  update_interval: 0.5s
  disp_bg_color: 0x000000
  #log_level: INFO
  top_layer:
    widgets:
      - label:
          text: "\uF1EB"
          id: lbl_wifi
          hidden: false
          align: top_right
          x: -2
          y: 7
          text_align: right
          text_color: 0xFF0000

binary_sensor:
  - platform: gpio
    name: charging
    device_class: battery_charging
    pin: 
      number: 21
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 1s

matrix_keypad:
  id: buttons
  rows:
    - pin: 
        number: 32
        allow_other_uses: true
    - pin: 
        number: 26
        allow_other_uses: true
    - pin: 
        number: 27
        allow_other_uses: true
    - pin: 
        number: 14
        allow_other_uses: true
    - pin: 
        number: 12
        allow_other_uses: true
  columns:
    - pin: 
        number: 37
        allow_other_uses: true
    - pin:  
        number: 38
        allow_other_uses: true
    - pin:  
        number: 39
        allow_other_uses: true
    - pin:  
        number: 34
        allow_other_uses: true
    - pin:  
        number: 35
        allow_other_uses: true
  has_diodes: False
  has_pulldowns: True
