script:
  - id: s1_source
    then:
      - logger.log: "Source Button Pressed"
  - id: s2_channel+
    then:
      - logger.log: "Channel+ Button Pressed"
  - id: s3_volume-
    then:
      - logger.log: "Volume- Button Pressed"
  - id: s4_mute
    then:
      - logger.log: "Mute Button Pressed"
  - id: s5_record
    then:
      - logger.log: "Record Buttom Pressed"
  - id: s6_info
    then:
      - logger.log: "Info Button Pressed"
  - id: s7_right
    then:
      - logger.log: "Right Buttton Pressed"
  - id: s8_volume+
    then:
      - logger.log: "Volume+ Button Pressed"
  - id: s9_ok
    then:
      - logger.log: "Ok Button Pressed"
  - id: s10_down
    then:
      - logger.log: "Down Button Pressed"
  - id: s11_blue
    then:
      - logger.log: "Blue Button Pressed"
  - id: s12_channel-
    then:
      - logger.log: "Channel- Button Pressed"
  - id: s13_red
    then:
      - logger.log: "Red Button Pressed"
  - id: s14_yellow
    then:
      - logger.log: "Yellow Button Pressed"
  - id: s15_green
    then:
      - logger.log: "Green Button Pressed"
  - id: s16_forward
    then:
      - logger.log: "Forward Button Pressed"
  - id: s18_back
    then:
      - logger.log: "Back Button Pressed"
  - id: s19_up
    then:
      - logger.log: "Up Button Pressed"
  - id: s20_left
    then:
      - logger.log: "Left Button Pressed"
  - id: s22_play
    then:
      - logger.log: "Play Button Pressed"
  - id: s23_config
    then:
      - logger.log: "Config Button Pressed"
  - id: s24_rewind
    then:
      - logger.log: "Rewind Button Pressed"
  - id: s25_stop
    then:
      - logger.log: "Stop Button Pressed"

binary_sensor:
  - platform: matrix_keypad
    name: source
    id: s1
    row: 0
    col: 0
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s1_source

  - platform: matrix_keypad
    name: channel+
    id: s2
    row: 1
    col: 0
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s2_channel+

  - platform: matrix_keypad
    name: Volume-
    id: s3
    row: 2
    col: 0
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s3_volume-

  - platform: matrix_keypad
    name: mute
    id: s4
    row: 3
    col: 0
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s4_mute

  - platform: matrix_keypad
    name: record
    id: s5
    row: 4
    col: 0
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s5_record

  - platform: matrix_keypad
    name: info
    id: s6
    row: 0
    col: 1
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s6_info

  - platform: matrix_keypad
    name: right
    id: s7
    row: 1
    col: 1
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s7_right

  - platform: matrix_keypad
    name: Volume+
    id: s8
    row: 2
    col: 1
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s8_volume+

  - platform: matrix_keypad
    name: OK
    id: s9
    row: 3
    col: 1
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s9_ok

  - platform: matrix_keypad
    name: down
    id: s10
    row: 4
    col: 1
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s10_down

  - platform: matrix_keypad
    name: blue
    id: s11
    row: 0
    col: 2
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s11_blue

  - platform: matrix_keypad
    name: channel-
    id: s12
    row: 1
    col: 2
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s12_channel-

  - platform: matrix_keypad
    name: red
    id: s13
    row: 2
    col: 2
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s13_red

  - platform: matrix_keypad
    name: yellow
    id: s14
    row: 3
    col: 2
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s14_yellow

  - platform: matrix_keypad
    name: green
    id: s15
    row: 4
    col: 2
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s15_green

  - platform: matrix_keypad
    name: forward
    id: s16
    row: 0
    col: 3
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s16_forward

  - platform: matrix_keypad
    name: off
    id: s17
    row: 1
    col: 3
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - deep_sleep.enter: ext1

  - platform: matrix_keypad
    name: back
    id: s18
    row: 2
    col: 3
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s18_back

  - platform: matrix_keypad
    name: up
    id: s19
    row: 3
    col: 3
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s19_up

  - platform: matrix_keypad
    name: left
    id: s20
    row: 4
    col: 3
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s20_left

  - platform: matrix_keypad
    name: play
    id: s22
    row: 1
    col: 4
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s22_play

  - platform: matrix_keypad
    name: config
    id: s23
    row: 2
    col: 4
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s23_config

  - platform: matrix_keypad
    name: rewind
    id: s24
    row: 3
    col: 4
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s24_rewind

  - platform: matrix_keypad
    name: stop
    id: s25
    row: 4
    col: 4
    on_press:
      - script.execute: ext1_coutdown
      - script.execute: s25_stop
